#!/bin/sh
rm -rf build
mkdir -p build
./node_modules/electron-packager/cli.js . $1 --platform=darwin --arch=x64 --version=0.28.3 --out=build --prune --asar --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --ignore=.git --ignore=resources
